name: langslice
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pillow
  - tifffile
  - pyside6
  - pip
  - pip:
    - antspyx
    - google-genai
    - brainglobe-atlasapi
    - python-dotenv
