from __future__ import annotations

import json
from pathlib import Path
from typing import Any, cast

import pytest

import langslice_harness.cli as cli
from langslice_harness.api.models import ENGINE_METHODS
from langslice_harness.api.typegen import (
    ENGINE_SCHEMA_PATH,
    ENGINE_TYPES_PATHS,
    build_contract_outputs,
    write_contract_outputs,
)


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def test_generated_engine_types_include_required_contract_symbols() -> None:
    bundle, engine_types = build_contract_outputs()
    typed_bundle = cast(dict[str, Any], bundle)
    union_values = " | ".join(f'"{method}"' for method in ENGINE_METHODS)
    engine_method_union = f"export type EngineMethod = {union_values};"
    assert 'export type Plane = "coronal" | "sagittal" | "horizontal";' in engine_types
    assert engine_method_union in engine_types
    assert typed_bundle["schemas"]["EngineRequest"]["properties"]["method"]["enum"] == list(
        ENGINE_METHODS
    )
    assert "export interface EngineRequest {" in engine_types
    assert "export interface RegisterResult {" in engine_types
    assert "export interface ExportResult {" in engine_types
    assert "export type WebDemoSupportedEngineMethod =" in engine_types
    assert "export const WEB_DEMO_SUPPORTED_ENGINE_METHODS" in engine_types


def test_write_contract_outputs_to_temp_dir(tmp_path: Path) -> None:
    schema_path, ts_paths = write_contract_outputs(project_root=tmp_path)
    assert schema_path == tmp_path / ENGINE_SCHEMA_PATH
    assert ts_paths == tuple(tmp_path / path for path in ENGINE_TYPES_PATHS)

    bundle = json.loads(schema_path.read_text(encoding="utf-8"))
    assert bundle["schema_version"] == "1"
    assert "EngineRequest" in bundle["schemas"]
    assert "ExportResult" in bundle["schemas"]

    for ts_path in ts_paths:
        text = ts_path.read_text(encoding="utf-8")
        assert "Generated by scripts/generate_engine_contract.py" in text
        assert "export interface EstimateRequest {" in text


def test_checked_in_contract_files_are_up_to_date() -> None:
    repo_root = _repo_root()
    bundle, engine_types = build_contract_outputs()

    expected_schema = json.dumps(bundle, indent=2, sort_keys=True) + "\n"
    actual_schema = (repo_root / ENGINE_SCHEMA_PATH).read_text(encoding="utf-8")
    assert actual_schema == expected_schema

    for relative_path in ENGINE_TYPES_PATHS:
        actual_types = (repo_root / relative_path).read_text(encoding="utf-8")
        assert actual_types == engine_types


def test_cli_schema_command_writes_schema_json(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    out_path = tmp_path / "custom" / "engine_schema.json"
    args = cli._build_parser().parse_args(["schema", "--out", str(out_path)])
    assert args.command == "schema"
    # Command writes all contract outputs relative to cwd.
    monkeypatch.chdir(tmp_path)
    cli.main(["schema", "--out", str(out_path)])
    bundle = json.loads(out_path.read_text(encoding="utf-8"))
    assert bundle["schema_version"] == "1"
    assert "EngineErrorEnvelope" in bundle["schemas"]
    for relative_path in ENGINE_TYPES_PATHS:
        assert (tmp_path / relative_path).exists()
