// Generated by scripts/generate_engine_contract.py. Do not edit by hand.

export type Plane = "coronal" | "sagittal" | "horizontal";
export type Provider = "google" | "openai";
export type PreprocessMode = "none" | "auto";
export type Workflow = "tool_use" | "image_gen";

export interface EngineError {
  code: string;
  message: string;
  details?: Record<string, unknown>;
}

export type EngineMethod = "version" | "estimate.run" | "register.run" | "quick_affine.run" | "export.run";

export interface EngineRequest {
  id: string;
  method: EngineMethod;
  params?: Record<string, unknown>;
}

export interface EngineProgressEvent {
  kind: "progress";
  message: string;
  stage?: string | null;
}

export interface EngineLogEvent {
  kind: "log";
  message: string;
}

export type EngineEvent = EngineProgressEvent | EngineLogEvent;

export interface EngineEventEnvelope {
  id: string;
  type: "event";
  event: EngineEvent;
}

export interface EngineResultEnvelope {
  id: string;
  type: "result";
  result?: Record<string, unknown>;
}

export interface EngineErrorEnvelope {
  id: string | null;
  type: "error";
  error: EngineError;
}

export type EngineEnvelope =
  | EngineEventEnvelope
  | EngineResultEnvelope
  | EngineErrorEnvelope;

export interface VersionResult {
  version: string;
}

export interface EstimateRequest {
  image_path: string;
  atlas: string;
  plane?: Plane;
  model?: string | null;
  thinking?: string | null;
  temperature?: number | null;
  media_resolution?: string | null;
  max_iterations?: number;
  preprocess?: PreprocessMode;
  provider?: Provider;
  endpoint?: string | null;
  output_dir?: string | null;
  workflow?: Workflow | null;
}

export interface EstimateResult {
  position_mm: number;
  reasoning: string;
  debug_dir?: string | null;
}

export interface RegisterRequest {
  image_path: string;
  atlas: string;
  position_mm: number;
  plane?: Plane;
  model?: string | null;
  image_model?: string | null;
  review_model?: string | null;
  thinking?: string | null;
  temperature?: number | null;
  preprocess?: PreprocessMode;
  provider?: Provider;
  endpoint?: string | null;
  output_dir?: string | null;
  max_iterations?: number;
  media_resolution?: string | null;
}

export interface RegisterResult {
  accepted_correspondence_count: number;
  rotation_deg: number;
  translation_px: [number, number];
  scale: [number, number];
  shear: number;
  debug_dir?: string | null;
  annotation_session?: Record<string, unknown> | null;
  warped_atlas_path?: string | null;
  warped_border_overlay_path?: string | null;
  generated_segmentation_path?: string | null;
  generated_border_overlay_path?: string | null;
  slice_warped_to_atlas_path?: string | null;
  slice_atlas_border_overlay_path?: string | null;
  inverse_warp_status?: string | null;
}

export interface QuickAffineRequest {
  image_path: string;
  atlas: string;
  position_mm: number;
  plane?: Plane;
  output_dir?: string | null;
  output_path?: string | null;
}

export interface QuickAffineResult {
  warped_slice_path: string;
  elapsed_s: number;
  silhouette_iou: number;
}

export interface ExportRequest {
  image_path: string;
  atlas: string;
  position_mm: number;
  output_path: string;
  affine_matrix?: number[][] | null;
  output_width?: number | null;
  output_height?: number | null;
  rotation_deg?: number;
  translate_x_pct?: number;
  translate_y_pct?: number;
}

export interface ExportResult {
  output_path: string;
  target: string;
  aligner: string;
  slices: number;
}

export type WebDemoSupportedEngineMethod = "version" | "estimate.run" | "quick_affine.run" | "register.run";

export const WEB_DEMO_SUPPORTED_ENGINE_METHODS: readonly WebDemoSupportedEngineMethod[] = ["version", "estimate.run", "quick_affine.run", "register.run"] as const;
