"""Generate engine schema and TypeScript contract artifacts."""

from __future__ import annotations

import json
from pathlib import Path

from langslice_harness.api.models import ENGINE_METHODS, export_schema_bundle

ENGINE_SCHEMA_PATH = Path("docs/engine_schema.json")
ENGINE_TYPES_PATHS = (
    Path("tauri-gui/src/lib/engineTypes.ts"),
    Path("web-demo/src/lib/engineTypes.ts"),
)
WEB_DEMO_ENGINE_METHODS = (
    "version",
    "estimate.run",
    "quick_affine.run",
    "register.run",
)
_REQUIRED_MODELS = (
    "EngineError",
    "EngineRequest",
    "EngineEventEnvelope",
    "EngineResultEnvelope",
    "EngineErrorEnvelope",
    "VersionResult",
    "EstimateRequest",
    "EstimateResult",
    "RegisterRequest",
    "RegisterResult",
    "QuickAffineRequest",
    "QuickAffineResult",
    "ExportRequest",
    "ExportResult",
)


def _literal_union(values: tuple[str, ...]) -> str:
    return " | ".join(f'"{value}"' for value in values)


def _extract_enum_values(
    bundle: dict[str, object],
    *,
    model_name: str,
    field_name: str,
) -> tuple[str, ...]:
    schemas = bundle["schemas"]
    assert isinstance(schemas, dict)
    schema = schemas[model_name]
    assert isinstance(schema, dict)
    properties = schema["properties"]
    assert isinstance(properties, dict)
    field_schema = properties[field_name]
    assert isinstance(field_schema, dict)

    enum_values: list[str] = []
    if isinstance(field_schema.get("enum"), list):
        enum_values = [str(value) for value in field_schema["enum"]]
    elif isinstance(field_schema.get("anyOf"), list):
        for option in field_schema["anyOf"]:
            if isinstance(option, dict) and isinstance(option.get("enum"), list):
                enum_values = [str(value) for value in option["enum"]]
                break

    if not enum_values:
        raise ValueError(f"No enum values found for {model_name}.{field_name}")
    return tuple(enum_values)


def generate_engine_types(bundle: dict[str, object]) -> str:
    plane_values = _extract_enum_values(bundle, model_name="EstimateRequest", field_name="plane")
    provider_values = _extract_enum_values(
        bundle,
        model_name="EstimateRequest",
        field_name="provider",
    )
    preprocess_values = _extract_enum_values(
        bundle,
        model_name="EstimateRequest",
        field_name="preprocess",
    )
    workflow_values = _extract_enum_values(
        bundle,
        model_name="EstimateRequest",
        field_name="workflow",
    )
    engine_methods = _literal_union(ENGINE_METHODS)
    web_demo_methods = _literal_union(WEB_DEMO_ENGINE_METHODS)
    plane = _literal_union(plane_values)
    provider = _literal_union(provider_values)
    preprocess = _literal_union(preprocess_values)
    workflow = _literal_union(workflow_values)
    web_demo_methods_array = ", ".join(f'"{value}"' for value in WEB_DEMO_ENGINE_METHODS)

    return (
        "// Generated by scripts/generate_engine_contract.py. Do not edit by hand.\n\n"
        f"export type Plane = {plane};\n"
        f"export type Provider = {provider};\n"
        f"export type PreprocessMode = {preprocess};\n"
        f"export type Workflow = {workflow};\n\n"
        "export interface EngineError {\n"
        "  code: string;\n"
        "  message: string;\n"
        "  details?: Record<string, unknown>;\n"
        "}\n\n"
        f"export type EngineMethod = {engine_methods};\n\n"
        "export interface EngineRequest {\n"
        "  id: string;\n"
        "  method: EngineMethod;\n"
        "  params?: Record<string, unknown>;\n"
        "}\n\n"
        "export interface EngineProgressEvent {\n"
        '  kind: "progress";\n'
        "  message: string;\n"
        "  stage?: string | null;\n"
        "}\n\n"
        "export interface EngineLogEvent {\n"
        '  kind: "log";\n'
        "  message: string;\n"
        "}\n\n"
        "export type EngineEvent = EngineProgressEvent | EngineLogEvent;\n\n"
        "export interface EngineEventEnvelope {\n"
        "  id: string;\n"
        '  type: "event";\n'
        "  event: EngineEvent;\n"
        "}\n\n"
        "export interface EngineResultEnvelope {\n"
        "  id: string;\n"
        '  type: "result";\n'
        "  result?: Record<string, unknown>;\n"
        "}\n\n"
        "export interface EngineErrorEnvelope {\n"
        "  id: string | null;\n"
        '  type: "error";\n'
        "  error: EngineError;\n"
        "}\n\n"
        "export type EngineEnvelope =\n"
        "  | EngineEventEnvelope\n"
        "  | EngineResultEnvelope\n"
        "  | EngineErrorEnvelope;\n\n"
        "export interface VersionResult {\n"
        "  version: string;\n"
        "}\n\n"
        "export interface EstimateRequest {\n"
        "  image_path: string;\n"
        "  atlas: string;\n"
        "  plane?: Plane;\n"
        "  model?: string | null;\n"
        "  thinking?: string | null;\n"
        "  temperature?: number | null;\n"
        "  media_resolution?: string | null;\n"
        "  max_iterations?: number;\n"
        "  preprocess?: PreprocessMode;\n"
        "  provider?: Provider;\n"
        "  endpoint?: string | null;\n"
        "  output_dir?: string | null;\n"
        "  workflow?: Workflow | null;\n"
        "}\n\n"
        "export interface EstimateResult {\n"
        "  position_mm: number;\n"
        "  reasoning: string;\n"
        "  debug_dir?: string | null;\n"
        "}\n\n"
        "export interface RegisterRequest {\n"
        "  image_path: string;\n"
        "  atlas: string;\n"
        "  position_mm: number;\n"
        "  plane?: Plane;\n"
        "  model?: string | null;\n"
        "  image_model?: string | null;\n"
        "  review_model?: string | null;\n"
        "  thinking?: string | null;\n"
        "  temperature?: number | null;\n"
        "  preprocess?: PreprocessMode;\n"
        "  provider?: Provider;\n"
        "  endpoint?: string | null;\n"
        "  output_dir?: string | null;\n"
        "  max_iterations?: number;\n"
        "  media_resolution?: string | null;\n"
        "}\n\n"
        "export interface RegisterResult {\n"
        "  accepted_correspondence_count: number;\n"
        "  rotation_deg: number;\n"
        "  translation_px: [number, number];\n"
        "  scale: [number, number];\n"
        "  shear: number;\n"
        "  debug_dir?: string | null;\n"
        "  annotation_session?: Record<string, unknown> | null;\n"
        "  warped_atlas_path?: string | null;\n"
        "  warped_border_overlay_path?: string | null;\n"
        "  generated_segmentation_path?: string | null;\n"
        "  generated_border_overlay_path?: string | null;\n"
        "  slice_warped_to_atlas_path?: string | null;\n"
        "  slice_atlas_border_overlay_path?: string | null;\n"
        "  inverse_warp_status?: string | null;\n"
        "}\n\n"
        "export interface QuickAffineRequest {\n"
        "  image_path: string;\n"
        "  atlas: string;\n"
        "  position_mm: number;\n"
        "  plane?: Plane;\n"
        "  output_dir?: string | null;\n"
        "  output_path?: string | null;\n"
        "}\n\n"
        "export interface QuickAffineResult {\n"
        "  warped_slice_path: string;\n"
        "  elapsed_s: number;\n"
        "  silhouette_iou: number;\n"
        "}\n\n"
        "export interface ExportRequest {\n"
        "  image_path: string;\n"
        "  atlas: string;\n"
        "  position_mm: number;\n"
        "  output_path: string;\n"
        "  affine_matrix?: number[][] | null;\n"
        "  output_width?: number | null;\n"
        "  output_height?: number | null;\n"
        "  rotation_deg?: number;\n"
        "  translate_x_pct?: number;\n"
        "  translate_y_pct?: number;\n"
        "}\n\n"
        "export interface ExportResult {\n"
        "  output_path: string;\n"
        "  target: string;\n"
        "  aligner: string;\n"
        "  slices: number;\n"
        "}\n\n"
        f"export type WebDemoSupportedEngineMethod = {web_demo_methods};\n\n"
        "export const WEB_DEMO_SUPPORTED_ENGINE_METHODS: readonly WebDemoSupportedEngineMethod[] = "
        f"[{web_demo_methods_array}] as const;\n"
    )


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _check_bundle_models(bundle: dict[str, object]) -> None:
    schemas = bundle.get("schemas")
    if not isinstance(schemas, dict):
        raise ValueError("Schema bundle is missing a dictionary 'schemas' entry")
    missing = [model_name for model_name in _REQUIRED_MODELS if model_name not in schemas]
    if missing:
        joined = ", ".join(missing)
        raise ValueError(f"Schema bundle is missing required models: {joined}")


def _dump_json(bundle: dict[str, object]) -> str:
    return json.dumps(bundle, indent=2, sort_keys=True) + "\n"


def build_contract_outputs() -> tuple[dict[str, object], str]:
    bundle = export_schema_bundle()
    _check_bundle_models(bundle)
    engine_types = generate_engine_types(bundle)
    return bundle, engine_types


def write_contract_outputs(
    *,
    project_root: Path,
    schema_path: Path = ENGINE_SCHEMA_PATH,
    engine_types_paths: tuple[Path, ...] = ENGINE_TYPES_PATHS,
) -> tuple[Path, tuple[Path, ...]]:
    bundle, engine_types = build_contract_outputs()
    resolved_schema_path = project_root / schema_path
    _write_text(resolved_schema_path, _dump_json(bundle))
    resolved_ts_paths: list[Path] = []
    for target in engine_types_paths:
        resolved = project_root / target
        _write_text(resolved, engine_types)
        resolved_ts_paths.append(resolved)
    return resolved_schema_path, tuple(resolved_ts_paths)
