"""LangSlice Atlas module - BrainGlobe atlas access as plain Python functions."""

from langslice_harness.atlas.core import (
    DEFAULT_ATLAS_NAME,
    canonicalize_atlas_name,
    get_additional_reference_slice,
    get_atlas_info,
    get_boundary_slice,
    get_colored_region_slice,
    get_composite_slice,
    get_position_range_mm,
    get_reference_slice,
    get_region_at_position,
    get_slice_region_metadata,
    get_smoothed_boundary_slice,
    get_structure_hierarchy,
    get_structure_mask_slice,
    index_to_position_mm,
    list_additional_references,
    list_available_atlases,
    list_downloaded_atlases,
    load_atlas,
    position_mm_to_index,
)

__all__ = [
    "load_atlas",
    "DEFAULT_ATLAS_NAME",
    "canonicalize_atlas_name",
    "position_mm_to_index",
    "index_to_position_mm",
    "get_position_range_mm",
    "get_reference_slice",
    "get_boundary_slice",
    "get_colored_region_slice",
    "get_composite_slice",
    "get_smoothed_boundary_slice",
    "list_additional_references",
    "get_additional_reference_slice",
    "get_region_at_position",
    "get_slice_region_metadata",
    "get_structure_hierarchy",
    "get_structure_mask_slice",
    "get_atlas_info",
    "list_available_atlases",
    "list_downloaded_atlases",
]
